name: Build and deploy

on:
  push:
    branches: [ main ]

    #Allow to run this workflow manually from the Actions tab in github
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: victorovich-inf-frontend
  DOCKER_BUILD_PATH: .
  DOCKERFILE: .docker/Dockerfile
  DOCKER_REGISTRY: ghcr.io/victorovich-inf

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Clone repository content
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Set Node.js 16.11.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.11.0'
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
        env:
          CI: false

      - name: Build and push docker container
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ env.DOCKERFILE }}
          context: ${{ env.DOCKER_BUILD_PATH }}
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository content
        uses: actions/checkout@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: frontend.yml
          directory: .ansible/
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory/nodes.yml
        env:
          IMAGE_VERSION: ${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG }}
          DOCKER_CREDENTIALS: ${{ secrets.DOCKER_CREDENTIALS }}